Repository Haesus/JDreamer-DJ, pull requests merged in 2024-06, with the labels that each got.

#2 [FEAT] DB & BackEnd Modeling 완료
  DJ(DailyJournal)-Node/Config/config.json
  DJ(DailyJournal)-Node/Models/index.js
  DJ(DailyJournal)-Node/Models/journal.js
  DJ(DailyJournal)-Node/Models/journalImage.js
  DJ(DailyJournal)-Node/Models/summary.js
  DJ(DailyJournal)-Node/Models/sync.js
  DJ(DailyJournal)-Node/Models/user.js
  DJ(DailyJournal)-Node/app.js
Labels: Feature, BackEnd

#3 [FEAT] BackEnd signRouter, authRouter 로직 구현 & user Model 수정
  DJ(DailyJournal)-Node/Models/journal.js
  DJ(DailyJournal)-Node/Models/journalImage.js
  DJ(DailyJournal)-Node/Models/summary.js
  DJ(DailyJournal)-Node/Models/user.js
  DJ(DailyJournal)-Node/Routers/authRouter.js
  DJ(DailyJournal)-Node/Routers/index.js
  DJ(DailyJournal)-Node/Routers/signRouter.js
  DJ(DailyJournal)-Node/app.js
Labels: Feature, BackEnd

#5 [FEAT] Journal logic 구현
  DJ(DailyJournal)-Node/Routers/authRouter.js
  DJ(DailyJournal)-Node/Routers/imageRouter.js
  DJ(DailyJournal)-Node/Routers/journalRouter.js
  DJ(DailyJournal)-Node/Routers/uploadImage.js
  DJ(DailyJournal)-Node/app.js
  DJ(DailyJournal)-Node/package-lock.json
  DJ(DailyJournal)-Node/package.json
Labels: Feature, BackEnd

#9 [FEAT] Xcode Groups 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
Labels: Feature, FrontEnd

#10 [FEAT] ColorExtension Add
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ColorExtension.swift
Labels: Feature, FrontEnd

#11 [FEAT] Color Extension backgroundColor 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ColorExtension.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
Labels: Feature, FrontEnd

#12 [FEAT] Azure AppService & DataBase 배포
  DJ(DailyJournal)-Node/.deployment
  DJ(DailyJournal)-Node/.vscode/settings.json
  DJ(DailyJournal)-Node/Config/config.js
  DJ(DailyJournal)-Node/Models/index.js
  DJ(DailyJournal)-Node/Models/sync.js
  DJ(DailyJournal)-Node/Routers/imageRouter.js
  DJ(DailyJournal)-Node/Routers/journalRouter.js
  DJ(DailyJournal)-Node/Routers/uploadImage.js
  DJ(DailyJournal)-Node/app.js
  DJ(DailyJournal)-Node/package-lock.json
  DJ(DailyJournal)-Node/package.json
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Labels: Feature, BackEnd

#14 [FEAT] DailyLogViwe add
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TestModel.swift
Labels: Feature, FrontEnd

#15 [FEAT] TabBarView 구현 #13
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Labels: Feature, FrontEnd

#16 [FEAT] TabBarView 수정 #13
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ColorExtension.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Labels: Feature, FrontEnd

#17 [FEAT] TitleExtension add
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TitleExtension.swift
Labels: Feature, FrontEnd

#21 SignInView 간단하게 구현
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Labels: Feature, FrontEnd

#22 [FEAT] Sign Logic 구현 #19
  .gitignore
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/BundleExtension.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/UserModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/SignService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/SignViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift
  DJ(DailyJournal)-Swift/DJ-DailyJournal--Info.plist
Labels: Feature, FrontEnd

#23 [FEAT] Journal Logic add
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/SignService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TestModel.swift
Labels: Feature, FrontEnd

#24 [FEAT] SignInView 디자인 수정 및 Alert 뷰 구현
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/SignViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/MainView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
Labels: Feature, FrontEnd

#27 [FEAT] TodoListView document 저장 로직 구현
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/TodoTemplateModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/TodoTemplate.json
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/TemplateViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Labels: Feature, FrontEnd

#29 [REFACTOR] 파일 위치 변경
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
Labels: Refactoring

#30 [FEAT] TabBarView.swift JournalListView 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/DetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/ListRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/ListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
Labels: Feature, FrontEnd

#32 Journal model, view, view model 수정
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/ListRowView.swift
Labels: Refactoring, FrontEnd

#33 [FEAT] 앨범에서 이미지 가져오는 로직 구현
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/DateExtension.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/TestModeling/ImageTestView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/AlbumImageViewModel.swift
Labels: Feature, FrontEnd

#34 [FEAT] DailyLogRowView의 배경색 변경
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogViews/DailyLogRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogViews/DailyLogView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignUpView.swift
Labels: Feature, FrontEnd

#36 [FEAT] Calendars Info 가져오는 로직 구현 #35
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/TestModeling/CalendarsTestView.swift
  DJ(DailyJournal)-Swift/DJ-DailyJournal--Info.plist
Labels: Feature, FrontEnd

#38 [FEAT] createJournalEntry 로직추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Labels: Feature, FrontEnd

#39 Journal text editing 기능 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/ImagePicker.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
Labels: FrontEnd

#40 AsyncImagesView.swift 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/AsyncImagesView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListRowView.swift
Labels: FrontEnd

#41 [FEAT] Notifications 로직 연동
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/DJ_DailyJournal_App.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/BackgroundFunc.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/NotificationViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
  DJ(DailyJournal)-Swift/DJ-DailyJournal--Info.plist
Labels: Feature, FrontEnd

#42 [FIX] Node Patch API FIX
  DJ(DailyJournal)-Node/Routers/journalRouter.js
Labels: Fix, BackEnd

#43 일기 수정 기능 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/AsyncImagesView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Labels: Feature, FrontEnd

#45 saveJournal 로직 구현
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/DJ_DailyJournal_App.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/DateExtension.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NotificationDelegate.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/TestModeling/CalendarsTestView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/TestModeling/ImageTestView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/AlbumImageViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/CalendarsViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/TemplateViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListRowView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Labels: Feature, FrontEnd

#44 JournalDetailView UI 수정
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
Labels: FrontEnd

#48 journalImages.count를 사용한 UpdatedJournal 모델 및 UpdatedJournalViewModel 수정
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
Labels: FrontEnd

#49 [FEAT] 앨범에서 사진 랜덤으로 가져오는 로직 추가 #25
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/AlbumImageViewModel.swift
Labels: Feature, FrontEnd

#50 DB 수정 및 Azure배포 완료
  DJ(DailyJournal)-Node/Routers/openaiRouter.js
  DJ(DailyJournal)-Node/package-lock.json
  DJ(DailyJournal)-Node/package.json
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Fix, BackEnd

#51 JournalDetailView.swift summary 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/SummaryModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Labels: Feature, FrontEnd

#53 일기 생성 시 AI Response Fetching 로직 추가
  DJ(DailyJournal)-Node/Routers/imageRouter.js
  DJ(DailyJournal)-Node/Routers/journalRouter.js
  DJ(DailyJournal)-Node/Routers/openaiRouter.js
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Labels: Feature, Refactoring, FrontEnd, BackEnd

#54 [REFACTOR] Design 부분 수정
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/ViewExtension.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/BackgroundFunc.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/TodoTemplate.json
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/SignViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TitleExtension.swift
Labels: Refactoring, FrontEnd

#57 JournalDetailView.swift 이미지 프레임 수정
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListRowView.swift
Labels: FrontEnd

#58 [FEAT] 로그아웃 후에 SignInView 전환
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SettingViews/SettingView.swift
Labels: Feature, FrontEnd

#59 [FEAT] Summary 관련 로직 수정
  DJ(DailyJournal)-Node/Models/summary.js
  DJ(DailyJournal)-Node/Routers/journalRouter.js
  DJ(DailyJournal)-Node/Routers/main.js
  DJ(DailyJournal)-Node/app.js
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SettingViews/SettingView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SettingViews/SummarySettingView.swift
Labels: FrontEnd, Fix, BackEnd

#61 [FEAT] Azure AI Vision & Swift JournalView 수정
  DJ(DailyJournal)-Node/Routers/analyzeImageFromUrl.js
  DJ(DailyJournal)-Node/Routers/journalRouter.js
  DJ(DailyJournal)-Node/Routers/main.js
  DJ(DailyJournal)-Node/package-lock.json
  DJ(DailyJournal)-Node/package.json
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/DateExtension.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/AlbumImageViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Labels: Feature, FrontEnd, BackEnd

#60 JournalListView.swift List 역순 정렬 추가
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Labels: FrontEnd

#62 [FEAT] AppIcon & LaunchScreenGIF Add
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
  DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/100.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/1024.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/114.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/120.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/128.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/144.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/152.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/16.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/167.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/172.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/180.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/196.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/20.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/216.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/256.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/29.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/32.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/40.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/48.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/50.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/512.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/55.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/57.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/58.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/60.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/64.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/66.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/72.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/76.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/80.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/87.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/88.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/92.png
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Assets.xcassets/AppIcon.appiconset/Contents.json
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/LaunchScreenViews/GIFImageView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/LaunchScreenViews/LaunchScreenGIF.gif
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/LaunchScreenViews/LaunchScreenView.swift
  DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/MainView.swift
Labels: Feature, FrontEnd
